# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["posts"]
# Output page's full content in RSS.
rssFullContent = false
favicon = "/stargate.ico"

[footer]
since = 2025
customText = "All rights reserved and attributions required."

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar]
emoji = "ðŸ“œ"
subtitle = "Let the dice roll and the adventures unfold!"

[sidebar.avatar]
enabled = true
local = true
src = "stargate.png"

[article]
headingAnchor = false
math = false
toc = true
readingTime = true

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"
